<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1"><!-- Begin Jekyll SEO tag v2.8.0 -->
<title>Python Exception Handling | My References</title>
<meta name="generator" content="Jekyll v3.9.2" />
<meta property="og:title" content="Python Exception Handling" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description." />
<meta property="og:description" content="Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description." />
<link rel="canonical" href="http://localhost:4000/python/exception_handling" />
<meta property="og:url" content="http://localhost:4000/python/exception_handling" />
<meta property="og:site_name" content="My References" />
<meta property="og:type" content="website" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:title" content="Python Exception Handling" />
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"WebPage","description":"Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.","headline":"Python Exception Handling","url":"http://localhost:4000/python/exception_handling"}</script>
<!-- End Jekyll SEO tag -->
<link rel="stylesheet" href="/assets/main.css"><link type="application/atom+xml" rel="alternate" href="http://localhost:4000/feed.xml" title="My References" /></head>
<body><header class="site-header" role="banner">

  <div class="wrapper"><a class="site-title" rel="author" href="/">My References</a><nav class="site-nav">
        <input type="checkbox" id="nav-trigger" class="nav-trigger" />
        <label for="nav-trigger">
          <span class="menu-icon">
            <svg viewBox="0 0 18 15" width="18px" height="15px">
              <path d="M18,1.484c0,0.82-0.665,1.484-1.484,1.484H1.484C0.665,2.969,0,2.304,0,1.484l0,0C0,0.665,0.665,0,1.484,0 h15.032C17.335,0,18,0.665,18,1.484L18,1.484z M18,7.516C18,8.335,17.335,9,16.516,9H1.484C0.665,9,0,8.335,0,7.516l0,0 c0-0.82,0.665-1.484,1.484-1.484h15.032C17.335,6.031,18,6.696,18,7.516L18,7.516z M18,13.516C18,14.335,17.335,15,16.516,15H1.484 C0.665,15,0,14.335,0,13.516l0,0c0-0.82,0.665-1.483,1.484-1.483h15.032C17.335,12.031,18,12.695,18,13.516L18,13.516z"/>
            </svg>
          </span>
        </label>

        <div class="trigger"></div>
      </nav></div>
</header>
<main class="page-content" aria-label="Content">
      <div class="wrapper">
        <article class="post">

  <header class="post-header">
    <h1 class="post-title">Python Exception Handling</h1>
  </header>

  <div class="post-content">
    <h2 id="syntax-summary-for-tryexcept">Syntax Summary For try/except</h2>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="n">statements</span> <span class="c1"># Run this main action first
</span><span class="k">except</span> <span class="n">name1</span><span class="p">:</span>
    <span class="n">statements</span> <span class="c1"># Run if name1 is raised during try block
</span><span class="k">except</span> <span class="p">(</span><span class="n">name2</span><span class="p">,</span> <span class="n">name3</span><span class="p">)</span>
    <span class="n">statements</span> <span class="c1"># Run if any of these exceptions occur
</span><span class="k">except</span> <span class="n">name4</span> <span class="k">as</span> <span class="n">var</span><span class="p">:</span>
    <span class="n">statements</span> <span class="c1"># Run if name4 is raised assign instance raised to var.
</span>               <span class="c1"># scope of var is limited to the except clause.
</span><span class="k">except</span><span class="p">:</span>
    <span class="n">statements</span> <span class="c1"># Run for all other exceptions raised
</span><span class="k">else</span><span class="p">:</span>
    <span class="n">statements</span> <span class="c1"># Run if no exceptions were raised in try block.
</span><span class="k">finally</span><span class="p">:</span>
    <span class="n">statements</span> <span class="c1"># Run no matter what and pass up error
</span></code></pre></div></div>

<h2 id="tryexcept">try/except</h2>

<p>Catch and recover from exception raised by Python or by you. Once you have caught the exception, control continues after the entire <code class="language-plaintext highlighter-rouge">try</code> that caught the exception, not after the statement that kicked it off. In fact Python clears the memory of any functions that were exited as a result of the exception.</p>

<h2 id="tryfinally">try/finally</h2>

<p>Perform cleanup actions weather an exception occurs or not.  If an exception <strong>does not</strong> occur while try block is running, Python continues on to run the finally block and then continues execution past the try statement.  If an exception <strong>does</strong> occur during the try block’s run, Python still comes back and runs the finally block, but it then propagates up the exception.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="n">fetcher</span><span class="p">(</span><span class="n">x</span><span class="p">,</span><span class="n">y</span><span class="p">)</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s">'after fetch'</span><span class="p">)</span> <span class="c1"># Will run weather exception is thrown or not.
</span></code></pre></div></div>

<p><code class="language-plaintext highlighter-rouge">finally</code> calls can be nested</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="o">&gt;&gt;&gt;</span> <span class="k">try</span><span class="p">:</span>
<span class="p">...</span>   <span class="k">try</span><span class="p">:</span>
<span class="p">...</span>     <span class="k">raise</span> <span class="nb">IndexError</span>
<span class="p">...</span>   <span class="k">finally</span><span class="p">:</span>
<span class="p">...</span>     <span class="k">print</span><span class="p">(</span><span class="s">'inner finally'</span><span class="p">)</span>
<span class="p">...</span> <span class="k">finally</span><span class="p">:</span>
<span class="p">...</span>   <span class="k">print</span><span class="p">(</span><span class="s">'outer finally'</span><span class="p">)</span>
<span class="p">...</span>
<span class="n">inner</span> <span class="k">finally</span>
<span class="n">outer</span> <span class="k">finally</span>
<span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s">"&lt;stdin&gt;"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">3</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
<span class="nb">IndexError</span>
<span class="o">&gt;&gt;&gt;</span>
</code></pre></div></div>

<h2 id="raise">raise</h2>

<p>Trigger an exception manually in your code</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="k">raise</span> <span class="nb">IndexError</span>
<span class="k">except</span> <span class="nb">IndexError</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s">'got exception'</span><span class="p">)</span>
</code></pre></div></div>

<h3 id="there-are-3-variations-of-raise">There are 3 variations of raise</h3>

<ul>
  <li>
    <p><code class="language-plaintext highlighter-rouge">raise IndexError()</code> Raises instance of class (lets you pass arguments)</p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">raise IndexError</code> Make and raise instance of class: makes an instance (if you don’t want to pass arguments)</p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">raise</code> Raise the most recent exception</p>
  </li>
</ul>

<h3 id="displaying-exceptions">Displaying Exceptions</h3>

<p>Any constructor arguments you pass to Exception classes or their children (via inheritance) are saved in the instances args tuple attribute, and are automatically displayed when the instances is printed. An empty tuple and display string is used if no constructor arguments are passed, and a single argument is displayed as itself, not a tuple.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="o">&gt;&gt;&gt;</span> <span class="k">raise</span> <span class="nb">IndexError</span>                       
<span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>         
    <span class="n">File</span> <span class="s">"&lt;stdin&gt;"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>      
<span class="nb">IndexError</span>                                 
<span class="o">&gt;&gt;&gt;</span> <span class="k">raise</span> <span class="nb">IndexError</span><span class="p">(</span><span class="s">'spam'</span><span class="p">)</span>               
<span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>         
    <span class="n">File</span> <span class="s">"&lt;stdin&gt;"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>      
<span class="nb">IndexError</span><span class="p">:</span> <span class="n">spam</span>                           
<span class="o">&gt;&gt;&gt;</span> <span class="n">I</span> <span class="o">=</span> <span class="nb">IndexError</span><span class="p">(</span><span class="s">'spam'</span><span class="p">)</span>                 
<span class="o">&gt;&gt;&gt;</span> <span class="n">I</span><span class="p">.</span><span class="n">args</span>                                 
<span class="p">(</span><span class="s">'spam'</span><span class="p">,)</span>                                  
<span class="o">&gt;&gt;&gt;</span> <span class="k">print</span><span class="p">(</span><span class="n">I</span><span class="p">)</span>                               
<span class="n">spam</span>                                       
<span class="o">&gt;&gt;&gt;</span> <span class="k">raise</span> <span class="nb">IndexError</span><span class="p">(</span><span class="s">"spam"</span><span class="p">,</span> <span class="s">'is'</span><span class="p">,</span> <span class="s">'ham'</span><span class="p">)</span>  
<span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>         
    <span class="n">File</span> <span class="s">"&lt;stdin&gt;"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>      
<span class="nb">IndexError</span><span class="p">:</span> <span class="p">(</span><span class="s">'spam'</span><span class="p">,</span> <span class="s">'is'</span><span class="p">,</span> <span class="s">'ham'</span><span class="p">)</span>          
<span class="o">&gt;&gt;&gt;</span>
</code></pre></div></div>

<h2 id="getting-exception-details-with-sysexc_info">Getting exception details with sys.exc_info</h2>

<p>If no exception is being handled a call to <code class="language-plaintext highlighter-rouge">sys.exc_info()</code> will return a tuple with 3 <code class="language-plaintext highlighter-rouge">None</code> elements.  If however an exception is being handled than you get a tuple with type, value and traceback.</p>

<p>Type is the exception class of the exception being handled.</p>

<p>Value is the exception class instance that was raised</p>

<p>Traceback is a <code class="language-plaintext highlighter-rouge">traceback</code> object that represents the call stack at the oint where the exception originally occurred, and ued by the traceback module to generate error messages.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="o">&gt;&gt;&gt;</span> <span class="kn">import</span> <span class="nn">sys</span>
<span class="o">&gt;&gt;&gt;</span> <span class="k">try</span><span class="p">:</span>
<span class="p">...</span>   <span class="k">print</span><span class="p">(</span><span class="s">"Ouch!"</span><span class="p">)</span>
<span class="p">...</span>   <span class="k">raise</span> <span class="nb">IndexError</span>
<span class="p">...</span> <span class="k">except</span><span class="p">:</span>
<span class="p">...</span>   <span class="n">exc_details</span> <span class="o">=</span> <span class="n">sys</span><span class="p">.</span><span class="n">exc_info</span><span class="p">()</span>
<span class="p">...</span>   <span class="k">print</span><span class="p">(</span><span class="sa">f</span><span class="s">"Type of exception is </span><span class="si">{</span><span class="n">exc_details</span><span class="p">[</span><span class="mi">0</span><span class="p">]</span><span class="si">}</span><span class="s">"</span><span class="p">)</span>
<span class="p">...</span>   <span class="k">print</span><span class="p">(</span><span class="sa">f</span><span class="s">"Value of exception is </span><span class="si">{</span><span class="n">exc_details</span><span class="p">[</span><span class="mi">1</span><span class="p">]</span><span class="si">}</span><span class="s">"</span><span class="p">)</span>
<span class="p">...</span>   <span class="k">print</span><span class="p">(</span><span class="sa">f</span><span class="s">"Traceback of exception is </span><span class="si">{</span><span class="n">exc_details</span><span class="p">[</span><span class="mi">2</span><span class="p">]</span><span class="si">}</span><span class="s">"</span><span class="p">)</span>
<span class="p">...</span>
<span class="n">Ouch</span><span class="err">!</span>
<span class="n">Type</span> <span class="n">of</span> <span class="n">exception</span> <span class="ow">is</span> <span class="o">&lt;</span><span class="k">class</span> <span class="err">'</span><span class="nc">IndexError</span><span class="s">'&gt;
Value of exception is
Traceback of exception is &lt;traceback object at 0x7f8811c741c0&gt;
&gt;&gt;&gt;
</span></code></pre></div></div>

<h2 id="built-in-exception-classes">Built in exception classes</h2>

<p><code class="language-plaintext highlighter-rouge">BaseException</code> - topmost root, printing and constructor defaults</p>

<p><code class="language-plaintext highlighter-rouge">Exception</code> - root of user defined exceptions</p>

<p><code class="language-plaintext highlighter-rouge">ArithmeticError</code> - root of numeric errors</p>

<p><code class="language-plaintext highlighter-rouge">LookupError</code> - root of indexing errors.</p>

<h2 id="user-defined-exceptions">User Defined Exceptions</h2>

<p>Exceptions are just object and being objects there are a number of benefits. Exception objects can be organized into catagories, have state information and behavior and they support inheritance. With inheritance you can <code class="language-plaintext highlighter-rouge">except</code> a certain exception type and match any subclass which can be convenient.</p>

<p><strong><em>Note</em></strong> To print a custom message overload the <code class="language-plaintext highlighter-rouge">__str__</code> and <code class="language-plaintext highlighter-rouge">__repr__</code> methods.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">AlreadyGotOne</span><span class="p">(</span><span class="nb">Exception</span><span class="p">):</span>
    <span class="k">def</span> <span class="nf">__str__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">return</span> <span class="s">'This is my custom error message'</span>

<span class="k">def</span> <span class="nf">grail</span><span class="p">():</span>
    <span class="k">raise</span> <span class="n">AlreadyGotOne</span>

<span class="k">try</span><span class="p">:</span> <span class="n">grail</span><span class="p">()</span>
<span class="k">except</span> <span class="n">AlreadyGotOne</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="sa">f</span><span class="s">'got exception: </span><span class="si">{</span><span class="n">e</span><span class="si">}</span><span class="s">'</span><span class="p">)</span>
</code></pre></div></div>

<p>Since exceptions are implemented as classes you can use the properties on those classes.  Below is a basic example.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code>    <span class="o">&gt;&gt;&gt;</span> <span class="k">class</span> <span class="nc">FormatError</span><span class="p">(</span><span class="nb">Exception</span><span class="p">):</span>                
    <span class="p">...</span>   <span class="k">def</span> <span class="nf">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">line</span><span class="p">,</span> <span class="nb">file</span><span class="p">):</span>            
    <span class="p">...</span>     <span class="bp">self</span><span class="p">.</span><span class="n">line</span> <span class="o">=</span> <span class="n">line</span>                         
    <span class="p">...</span>     <span class="bp">self</span><span class="p">.</span><span class="nb">file</span> <span class="o">=</span> <span class="nb">file</span>                         
    <span class="p">...</span>                                              
    <span class="o">&gt;&gt;&gt;</span> <span class="k">def</span> <span class="nf">parser</span><span class="p">():</span>                                
    <span class="p">...</span>   <span class="k">raise</span> <span class="n">FormatError</span><span class="p">(</span><span class="mi">42</span><span class="p">,</span> <span class="nb">file</span><span class="o">=</span><span class="s">'spam.txt'</span><span class="p">)</span>     
    <span class="p">...</span>                                              
    <span class="o">&gt;&gt;&gt;</span> <span class="k">try</span><span class="p">:</span>                                         
    <span class="p">...</span>   <span class="n">parser</span><span class="p">()</span>                                   
    <span class="p">...</span> <span class="k">except</span> <span class="n">FormatError</span> <span class="k">as</span> <span class="n">X</span><span class="p">:</span>                     
    <span class="p">...</span>   <span class="k">print</span><span class="p">(</span><span class="s">'Error at: %s %s'</span> <span class="o">%</span> <span class="p">(</span><span class="n">X</span><span class="p">.</span><span class="nb">file</span><span class="p">,</span> <span class="n">X</span><span class="p">.</span><span class="n">line</span><span class="p">))</span>
    <span class="p">...</span>                                              
<span class="n">Error</span> <span class="n">at</span><span class="p">:</span> <span class="n">spam</span><span class="p">.</span><span class="n">txt</span> <span class="mi">42</span>
</code></pre></div></div>

<h2 id="assert">assert</h2>

<p>The <code class="language-plaintext highlighter-rouge">assert</code> statement lets you conditionally trigger an exception in your code.</p>

<p>The syntax is <code class="language-plaintext highlighter-rouge">assert test data</code> where the data part is optional.</p>

<p>If the test validates false, Python raises an exception.  The data item if provided is used as the exception’s constructor argument.  Like all exceptions an <code class="language-plaintext highlighter-rouge">AssertionError</code> will kill your program if not caught with a <code class="language-plaintext highlighter-rouge">try</code>.</p>

<p>Assertions are typically used to verify program conditions during development. When displayed their error messages automatically include source code line information and the value listed in the assert statement. Python will trap programming errors so you want to use assert for user defined restrictions.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="o">&gt;&gt;&gt;</span> <span class="k">def</span> <span class="nf">f</span><span class="p">(</span><span class="n">x</span><span class="p">):</span>
<span class="p">...</span>   <span class="k">assert</span> <span class="n">x</span><span class="o">&lt;</span><span class="mi">0</span><span class="p">,</span> <span class="s">'x must be negative'</span>
<span class="p">...</span>   <span class="k">return</span> <span class="n">x</span> <span class="o">**</span> <span class="mi">2</span>
<span class="p">...</span>
<span class="o">&gt;&gt;&gt;</span> <span class="n">f</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
<span class="n">Traceback</span> <span class="p">(</span><span class="n">most</span> <span class="n">recent</span> <span class="n">call</span> <span class="n">last</span><span class="p">):</span>
  <span class="n">File</span> <span class="s">"&lt;stdin&gt;"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">1</span><span class="p">,</span> <span class="ow">in</span> <span class="o">&lt;</span><span class="n">module</span><span class="o">&gt;</span>
  <span class="n">File</span> <span class="s">"&lt;stdin&gt;"</span><span class="p">,</span> <span class="n">line</span> <span class="mi">2</span><span class="p">,</span> <span class="ow">in</span> <span class="n">f</span>
<span class="nb">AssertionError</span><span class="p">:</span> <span class="n">x</span> <span class="n">must</span> <span class="n">be</span> <span class="n">negative</span>
</code></pre></div></div>

<h2 id="exception-usage-idioms">Exception Usage Idioms</h2>

<h3 id="exceptions-arent-always-errors">Exceptions aren’t always errors</h3>

<p>In Python all errors are exceptions but not all exceptions are errors. For example we can use exceptions to signal an end of file.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">while</span> <span class="bp">True</span><span class="p">:</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">line</span> <span class="o">=</span> <span class="nb">input</span><span class="p">()</span>
    <span class="k">except</span><span class="p">:</span> <span class="nb">EOFError</span><span class="p">:</span>
        <span class="k">break</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="p">...</span> <span class="c1"># process next line here
</span></code></pre></div></div>

<h3 id="functions-can-signal-conditions-with-a-raise">Functions can signal conditions with a raise</h3>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">class</span> <span class="nc">Found</span><span class="p">(</span><span class="nb">Exception</span><span class="p">):</span>
    <span class="k">pass</span>

<span class="k">def</span> <span class="nf">searcher</span><span class="p">():</span>
    <span class="k">if</span> <span class="p">...</span><span class="n">success</span><span class="p">...:</span>
        <span class="k">raise</span> <span class="n">Found</span><span class="p">()</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="k">return</span>

<span class="k">try</span><span class="p">:</span>
    <span class="n">searcher</span><span class="p">()</span>
<span class="k">except</span> <span class="n">Found</span><span class="p">:</span>
<span class="k">else</span><span class="p">:</span>
    <span class="p">...</span><span class="n">failure</span><span class="p">..</span>
</code></pre></div></div>

<h3 id="closing-files-and-server-connections">Closing files and server connections</h3>

<p>This is just an example as you can do this more efficiently but the flow of control for cleaning up resources is …</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">my_file</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="s">'my_file.txt'</span><span class="p">,</span> <span class="s">'w'</span><span class="p">):</span>
<span class="k">try</span><span class="p">:</span>
    <span class="p">...</span> <span class="n">process</span> <span class="n">my_file</span><span class="p">...</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="n">my_file</span><span class="p">.</span><span class="n">close</span><span class="p">()</span>
</code></pre></div></div>

<h3 id="debugging-with-outer-try-statement">Debugging with outer try statement</h3>

<p>You can wrap your programs with a try/except to debug.  The below structure is commonly used during development to keep programs active even if errors occur within a loop.  It allows you to run additional tests without having to restart.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="p">...</span> <span class="n">run</span> <span class="n">program</span> <span class="p">...</span>
<span class="k">except</span><span class="p">:</span>
    <span class="kn">import</span> <span class="nn">sys</span>
    <span class="k">print</span><span class="p">(</span><span class="s">"uncaught!"</span><span class="p">,</span> <span class="n">sys</span><span class="p">.</span><span class="n">exc_info</span><span class="p">()[</span><span class="mi">0</span><span class="p">],</span> <span class="n">sys</span><span class="p">.</span><span class="n">exc_info</span><span class="p">()[</span><span class="mi">1</span><span class="p">])</span>
</code></pre></div></div>

<p>Below is a sample test driver application</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kn">import</span> <span class="nn">sys</span>
<span class="n">log</span> <span class="o">=</span> <span class="nb">open</span><span class="p">(</span><span class="s">'testlog'</span><span class="p">,</span> <span class="s">'a'</span><span class="p">)</span>
<span class="kn">from</span> <span class="nn">testapi</span> <span class="kn">import</span> <span class="n">moreTests</span><span class="p">,</span> <span class="n">runNextTest</span><span class="p">,</span> <span class="n">testName</span>
<span class="k">def</span> <span class="nf">testdriver</span><span class="p">():</span>
    <span class="k">while</span> <span class="n">moreTests</span><span class="p">():</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="n">runNextTest</span><span class="p">()</span>
        <span class="k">except</span><span class="p">:</span>
            <span class="k">print</span><span class="p">(</span><span class="s">'FAILED'</span><span class="p">,</span> <span class="n">testName</span><span class="p">(),</span> <span class="n">sys</span><span class="p">.</span><span class="n">exc_info</span><span class="p">()[:</span><span class="mi">2</span><span class="p">],</span> <span class="nb">file</span><span class="o">=</span><span class="n">log</span><span class="p">)</span>
        <span class="k">else</span><span class="p">:</span>
            <span class="k">print</span><span class="p">(</span><span class="s">'PASSED'</span><span class="p">,</span> <span class="n">testName</span><span class="p">(),</span> <span class="nb">file</span><span class="o">=</span><span class="n">log</span><span class="p">)</span>

<span class="n">testDriver</span><span class="p">()</span>
</code></pre></div></div>

<h3 id="be-careful-not-to-catch-exceptions-that-should-terminate-the-program">Be careful not to catch exceptions that should terminate the program</h3>

<p>In the example below the program should exit, but since we are catching the exception it is allowed to continue.</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kn">import</span> <span class="nn">sys</span>
<span class="k">def</span> <span class="nf">bye</span><span class="p">():</span>
    <span class="n">sys</span><span class="p">.</span><span class="nb">exit</span><span class="p">(</span><span class="mi">40</span><span class="p">)</span>

<span class="k">try</span><span class="p">:</span>
    <span class="n">bye</span><span class="p">()</span>
<span class="k">except</span><span class="p">:</span>
    <span class="k">print</span><span class="p">(</span><span class="s">'got it'</span><span class="p">)</span>
<span class="k">print</span><span class="p">(</span><span class="s">'continuing...'</span><span class="p">)</span>
</code></pre></div></div>

<p>The correct way would be to do this …</p>

<div class="language-python highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">try</span><span class="p">:</span>
    <span class="n">bye</span><span class="p">()</span>
<span class="k">except</span> <span class="nb">Exception</span><span class="p">:</span> <span class="c1"># Won't catch exits, but will catch many other errors.
</span></code></pre></div></div>

  </div>

</article>

      </div>
    </main><footer class="site-footer h-card">
  <data class="u-url" href="/"></data>

  <div class="wrapper">

    <h2 class="footer-heading">My References</h2>

    <div class="footer-col-wrapper">
      <div class="footer-col footer-col-1">
        <ul class="contact-list">
          <li class="p-name">My References</li><li><a class="u-email" href="mailto:your-email@example.com">your-email@example.com</a></li></ul>
      </div>

      <div class="footer-col footer-col-2"><ul class="social-media-list"><li><a href="https://github.com/jekyll"><svg class="svg-icon"><use xlink:href="/assets/minima-social-icons.svg#github"></use></svg> <span class="username">jekyll</span></a></li><li><a href="https://www.twitter.com/jekyllrb"><svg class="svg-icon"><use xlink:href="/assets/minima-social-icons.svg#twitter"></use></svg> <span class="username">jekyllrb</span></a></li></ul>
</div>

      <div class="footer-col footer-col-3">
        <p>Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.</p>
      </div>
    </div>

  </div>

</footer>
</body>

</html>
